export const DELETE_TODO = 'todoList/delete_toto'
export const ADD_TODO = 'todoList/add_todo'
export const INPUT_CHANGE = 'todoList/input_change'
export const SET_FILTER = 'todoList/set_filter'
export const SET_GETLIST = 'todoList/getList'