GET http://111.230.173.173:80/common/media/play?deviceNo=KT_LAW_12&streamClarity=2&publishProto=2

###
POST http://111.230.173.173/common/device/gps/list
Content-Type: application/json

["KT_LAW_11","KT_LAW_12","KT_LAW_13","KT_LAW_14"]

###
POST http://111.230.173.173:80/common/device/law
Content-Type: application/json

# ["KT_LAW_11","KT_LAW_12","KT_LAW_13","KT_LAW_14"]